In [6]:
import pandas as pd
import sqlite3
from pprint import pprint

# caminho para o banco de dados
db_path = '../data/contos.sqlite'
conn = sqlite3.connect(db_path)

In [2]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
display(tables)

                  name
0                tales
1      sqlite_sequence
2       classificacoes
3  conto_classificacao

In [4]:
df_tales = pd.read_sql_query("SELECT * FROM tales", conn)

display(df_tales.head(3))

,id,titulo,origem,url,texto_completo
0,1,The Birth of Aistulf,Jacob and Wilhelm Grimm,https://sites.pitt.edu/~dash/manykids.html,The following legend is told about King Aistul...
1,2,As Many Children as There Are Days in the Year,Jacob and Wilhelm Grimm,https://sites.pitt.edu/~dash/manykids.html,Loosduynen (Leusden) is a small village one mi...
2,3,The Woman with Three Hundred and Sixty-Six \nC...,Netherlands,https://sites.pitt.edu/~dash/manykids.html,"So, because the forests of oak, and beech, and..."

In [51]:
len(df_tales)

1683

In [86]:
df_links = df_tales[df_tales['origem'].str.contains("N/A", na=False)]
display(df_links)

,id,titulo,origem,url,texto_completo
36,38,Links to Related Sites,N/A,https://sites.pitt.edu/~dash/type0510b.html,"Notes and BibliographyIn their classical form,..."
37,39,Notes and Bibliography,N/A,https://sites.pitt.edu/~dash/type0510b.html,"In their classical form, type 510B folktales i..."
38,40,Human Sacrifice among the Gauls,N/A,https://sites.pitt.edu/~dash/sacrifice.html,Source:Caesar's Commentaries on the Gallic War...
59,61,Merseburger Zaubersprüche,N/A,https://sites.pitt.edu/~dash/merseburg.html,
60,62,1.,N/A,https://sites.pitt.edu/~dash/merseburg.html,"Once the Idisi set forth, to this place and th..."
...,...,...,...,...,...
1546,1622,Prologue,N/A,https://sites.pitt.edu/~dash/beowulf.html,Scyld died at the fated time. Following his w...
1553,1629,Related links,N/A,https://sites.pitt.edu/~dash/type1288a.html,Return to thetable of contents.Return to D. L....
1567,1643,Of Hearing Good Counsel,N/A,https://sites.pitt.edu/~dash/type0150.html,"An archer, catching a little bird called a nig..."
1589,1665,Jacob and Wilhelm Grimm,N/A,https://sites.pitt.edu/~dash/grimm116a.html,a comparison of the versions of 1815 and 1857c...
1614,1692,Notes and Bibliography,N/A,https://sites.pitt.edu/~dash/midwife.html,"""Midwife (or Godparent) for the Elves"" tales a..."

In [128]:
condition = df_tales['origem'].str.contains("N/A", na=False)
display(df_tales.loc[condition, ['titulo', 'url', 'origem', 'texto_completo']])

,titulo,url,origem,texto_completo
97,The Little Sister: The Story of Suyettar and t...,https://sites.pitt.edu/~dash/type0451.html,N/A,FinlandThere was once a woman who had nine son...
98,The Twelve Wild Geese,https://sites.pitt.edu/~dash/type0451.html,N/A,IrelandThere was once a king and queen that li...
278,Three Little Red Pigs,https://sites.pitt.edu/~dash/type0850.html,N/A,DenmarkOnce upon a time there was an old woman...
283,Many Things Can Be Achieved through Beautiful ...,https://sites.pitt.edu/~dash/type0850.html,N/A,SlavicOnce an emperor had an only daughter of ...
289,Dshahan and the Three Pigs,https://sites.pitt.edu/~dash/type0850.html,N/A,MaltaIn Dshahan's time pigs were very expensiv...
373,Links to Additional Type 57 Fables,https://sites.pitt.edu/~dash/type0057.html,N/A,Aesop.The \nRaven and the Fox. InThe \nFables ...
448,The Brave Flute Player,https://sites.pitt.edu/~dash/type0326.html,N/A,GermanyOnce upon a time there was a merry musi...
450,The Boy Who Did Not Know What Fear Was,https://sites.pitt.edu/~dash/type0326.html,N/A,IcelandThere was once a boy so courageous and ...
451,Jack Dreadnought,https://sites.pitt.edu/~dash/type0326.html,N/A,HungaryA poor widow had a son who was so coura...
452,The Boy Who Found Fear at Last,https://sites.pitt.edu/~dash/type0326.html,N/A,TurkeyOnce upon a time there lived a woman who...
453,The Deadly Mosque,https://sites.pitt.edu/~dash/type0326.html,N/A,PersiaIn the suburbs of a certain city there w...
455,The Headless Dwarfs,https://sites.pitt.edu/~dash/type0326.html,N/A,EstoniaThere was once a minister who spent his...
461,The Dismembered Ghost,https://sites.pitt.edu/~dash/type0326.html,N/A,"USAOnce there was a man, an' he wanted a place..."
462,The Haunted House,https://sites.pitt.edu/~dash/type0326.html,N/A,USA (North Carolina)Come along a woman with th...
585,and other legendsabout human hands,https://sites.pitt.edu/~dash/hand.html,N/A,folktales of type 958E*edited and/or translate...
683,Links to related sites.,https://sites.pitt.edu/~dash/magicbook.html,N/A,The Black School. \nMigratory legends of type ...
717,The Indian Cinderella,https://sites.pitt.edu/~dash/type0510a.html,N/A,Strong Wind used a clever trick to test the tr...
748,The Doctor and Death,https://sites.pitt.edu/~dash/type0332.html,N/A,DenmarkThere was a very poor man who had to ma...
897,Buttermilk Jack,https://sites.pitt.edu/~dash/type1430.html,N/A,"Ther wur an owld 'oman as had but one son,And ..."
1160,The Sky Is Falling,https://sites.pitt.edu/~dash/type2033.html,N/A,folktales of Aarne-Thompson-Uther type 20C(inc...
1456,Of the Remembrance of Benefits,https://sites.pitt.edu/~dash/type0156.html,N/A,There was a knight who devoted much of his tim...
1567,Of Hearing Good Counsel,https://sites.pitt.edu/~dash/type0150.html,N/A,"An archer, catching a little bird called a nig..."

In [124]:
df_tales = df_tales[df_tales['titulo'] != "Links to related sites"]
df_tales = df_tales[df_tales['titulo'] != "Related links"]
df_tales = df_tales[df_tales['titulo'] != "Links to Related Sites"]
df_tales = df_tales[df_tales['titulo'] != "Notes and Bibliography"]
df_tales = df_tales[df_tales['texto_completo'].str.len() >= 100]
palavras_proibidas = ['Source', 'Return', 'Footnotes', 'Additional ']
df_tales = df_tales[~df_tales['texto_completo'].str.startswith(tuple(palavras_proibidas), na=False)]
url_para_remover = [
    'https://sites.pitt.edu/~dash/censor.html',
    'https://sites.pitt.edu/~dash/sacrifice.html',
    'https://sites.pitt.edu/~dash/changeling.html',
    'https://sites.pitt.edu/~dash/ashliman.html',
    'https://sites.pitt.edu/~dash/paiute.html',
    'https://sites.pitt.edu/~dash/cupid.html',
    'https://sites.pitt.edu/~dash/aging.html',
    'https://sites.pitt.edu/~dash/folklinks.html',
]
df_tales = df_tales[~df_tales['url'].isin(url_para_remover)]
# Verifica se foram removidas (o count deve ser 0 agora)
print(len(df_tales))

1403

In [127]:
df_links = df_tales[df_tales['origem'].str.contains("N/A", na=False)]
# Exibe os valores únicos da coluna 'url'
unique_urls = df_links['url'].unique()
display(unique_urls)

array(['https://sites.pitt.edu/~dash/type0451.html',
       'https://sites.pitt.edu/~dash/type0850.html',
       'https://sites.pitt.edu/~dash/type0057.html',
       'https://sites.pitt.edu/~dash/type0326.html',
       'https://sites.pitt.edu/~dash/hand.html',
       'https://sites.pitt.edu/~dash/magicbook.html',
       'https://sites.pitt.edu/~dash/type0510a.html',
       'https://sites.pitt.edu/~dash/type0332.html',
       'https://sites.pitt.edu/~dash/type1430.html',
       'https://sites.pitt.edu/~dash/type2033.html',
       'https://sites.pitt.edu/~dash/type0156.html',
       'https://sites.pitt.edu/~dash/type0150.html'], dtype=object)

In [ ]:
# remover linhas com
[
    'https://sites.pitt.edu/~dash/censor.html',
    'https://sites.pitt.edu/~dash/sacrifice.html',
    'https://sites.pitt.edu/~dash/changeling.html',
    'https://sites.pitt.edu/~dash/ashliman.html',
    'https://sites.pitt.edu/~dash/paiute.html',
    'https://sites.pitt.edu/~dash/cupid.html',
]

# título contem "Link"

In [85]:
df_tales = df_tales[df_tales['titulo'] != "Related Links"]
# Verifica se foram removidas (o count deve ser 0 agora)
print(len(df_tales[df_tales['origem'] == "N/A"]))
print(df_tales.shape)

211
(1636, 5)

In [126]:
condition = df_tales['url'].str.contains("dwarf", na=False)
# Atualiza a coluna 'origem' onde a condição é verdadeira
df_tales.loc[condition, 'origem'] = 'Switzerland'
# Verifica o resultado
display(df_tales.loc[condition, ['titulo', 'url', 'origem']])

,titulo,url,origem
1398,Tod der sieben Zwerge,https://sites.pitt.edu/~dash/dwarfs.html,Switzerland

In [63]:
example = df_tales.sample(1)
print(example['titulo'].iloc[0]+'\n')
print(example['origem'].iloc[0]+'\n')
pprint(example['texto_completo'].iloc[0])

Links to related sites

N/A

'Revised September 11, 2018.'

In [130]:
from pathlib import Path

In [132]:
contos_semi_limpos = Path.cwd().parent / 'data' / 'contos_semi_limpos.csv'

In [133]:
df_tales.to_csv(contos_semi_limpos, index=False)