In [77]:
import pandas as pd
import sqlite3

# caminho para o banco de dados
db_path = '../data/contos_propp_v2.sqlite'
db_path_contos = '../data/contos.sqlite'
conn = sqlite3.connect(db_path)
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
display(tables)

                        name
0                      tales
1            sqlite_sequence
2          tale_translations
3                       tags
4           tag_translations
5                  tale_tags
6                   entities
7        entity_translations
8          analysis_metadata
9            booker_analysis
10            propp_analysis
11  propp_clustering_results

In [78]:
df = pd.read_sql_query("SELECT * FROM propp_clustering_results", conn)

display(df.sample(3))

      tale_id       method  cluster_id     score
2403       51  levenshtein           0  0.170015
1242       75      bigrams           0  0.074784
2697      395  levenshtein           1  0.170015